dist: bionic

language: cpp

before_install:
  - sudo apt-get -y install libcgal-dev openmpi cmake gcc make

#install: gcc make cmake

compiler: gcc

before_script: cmake .

script:
  - make
  - make test